[workspace]
members = [
        "tokio-thrift-lib",
        "tokio-thrift-codegen",
        "tokio-thrift-bin",
        "examples/simple_server_client",
        ]

[replace]
"tokio-thrift:0.1.0" = { path = "tokio-thrift-lib" }
"tokio-thrift-codegen:0.1.0" = { path = "tokio-thrift-codegen" }
