[package]
name = "thrust"
version = "0.0.1"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[dependencies]
byteorder = "*"
docopt = "0.6"
rustc-serialize = "0.3"

[dependencies.nom]
git = "https://github.com/Geal/nom"
