[package]
name = "thrust_macros"
version = "0.1.0"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[lib]
crate-type = ["dylib"]
name = "thrust_macros"
path = "src/lib.rs"
plugin = true

[dependencies.thrust_parser]
path = "../thrust-parser"
