[package]
name = "tokio-thrift-codegen"
version = "0.1.0"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>", "Sunrin SHIMURA (keen) <3han5chou7@gmail.com>"]
workspace = "../"

[dependencies]
handlebars = "^0.22"
rustc-serialize = "^0.3.15"