[package]
authors = ["Daniel Fagnan <dnfagnan@gmail.com>", "Sunrin SHIMURA (keen) <3han5chou7@gmail.com>"]
name = "tokio-thrift-codegen"
version = "0.1.0"
workspace = "../"

[dependencies]
handlebars = "^0.22"
nom = "1.2.4"
rustc-serialize = "^0.3.15"
