[package]
name = "thrust_macros_test"
version = "0.1.0"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[dependencies]

[dependencies.thrust_macros]
path = "../thrust-macros"

[dependencies.thrust]
path = ".."
