[package]
name = "tokio-thrift-macros"
version = "0.1.0"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[lib]
crate-type = ["dylib"]
name = "tokio_thrift_macros"
path = "src/lib.rs"
plugin = true

[dependencies.tokio-thrift-parser]
path = "../tokio-thrift-parser"
