[package]
name = "tokio-thrift-macros-test"
version = "0.1.0"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[dependencies]
tangle = "*"

[dependencies.tokio-thrift-macros]
path = "../tokio-thrift-macros"

[dependencies.tokio-thrift]
path = ".."
